### ISSUE TITLE
Remove unrar

### ISSUE THREAD

**Issue by mimi89999** [mar-v-in/freecyngn#37]
The binary is in `/system/xbin/unrar`
> serranoltexx:/ $ /system/xbin/unrar --help                                                                                                 

> UNRAR 4.20 freeware      Copyright (c) 1993-2012 Alexander Roshal

Full license: https://github.com/LineageOS/android_external_unrar/blob/cm-14.1/NOTICE

It isn't free software (as freedom), so it should also be removed by the script.

**Comment by andrewrabert** [comment]
While the license isn't ideal, the source code is available and it doesn't include tracking, goblins, etc.

If you need a fully free distribution of Android in terms of license, see [Replicant](http://www.replicant.us/).
